---
title: "README"
author: "Mariona"
date: "20/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Dataset

Human Activity Recognition Using Smartphones

## Files

  * CodeBook.md that describes the variables, the data, and any transformations or work that you performed to clean        up the data
  
  * README.md explains how all of the scripts work and how they are connected.

  * run_analysis.R is the script to create the tidy data following the 5 steps required as described in the course         project’s definition:
                + Merges the training and the test sets to create one data set.
                + Extracts only the measurements on the mean and standard deviation for each measurement.
                + Uses descriptive activity names to name the activities in the data set
                + Appropriately labels the data set with descriptive variable names.
                + From the data set in step 4, creates a second, independent tidy data set with the average of each                      variable for each activity and each subject.
                
   * tidydata.txt is the exported final data after run the script.